[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
api = { workspace = true }
pulldown-cmark = "0.9"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "MediaQueryList", "Storage"] }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
