[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
api = { workspace = true }
web-sys = { version = "0.3", features = ["Window", "MediaQueryList"] }
gloo-file = { version = "0.3", features = ["futures"] }
base64 = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
